config/routes.rb
Store::Application.routes.draw do
  resources :users do
    post 'filter_panel', :on => :collection
    get 'show_info_table', :on => :member
    get 'show_sells', :on => :member
    get 'show_bought', :on => :member
    get 'show_sold', :on => :member
    post 'select_table', :on => :member
  end
  resources :lists do
    post 'filter_panel', :on => :collection
  end
  root to: 'lists#index'
end

app/models/archive.rb
class Archive < ActiveRecord::Base
  attr_protected
  # attr_accessible :title, :body
  self.table_name = "archive"
  self.primary_key  = "ListingId"
  has_one :seller, :class_name => 'Users', :foreign_key => "Id", :primary_key => "SellerId"
  has_one :buyer, :class_name => 'Users', :foreign_key => "Id", :primary_key => "BuyerId"
end

app/models/bids.rb
class Bids < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = "bids"
  self.primary_keys= :ListingId, :User
  belongs_to :users, :foreign_key => "User", :primary_key => "Id"
end

app/models/consumer_token.rb
require 'oauth/models/consumers/token'
class ConsumerToken < ActiveRecord::Base
  include Oauth::Models::Consumers::Token

  # You can safely remove this callback if you don't allow login from any of your services
  before_create :create_user

  # Modify this with class_name etc to match your application
  belongs_to :user

end

app/models/list.rb
class List < ActiveRecord::Base
  self.table_name = "lists"
  self.primary_key  = "ListingId"
  has_one :users, :foreign_key => "Id", :primary_key => "SellerId"
  scope :users_included, includes(:users).where("lists.SellerId = users.Id")
end

app/models/notifications.rb
class Notifications < ActiveRecord::Base
  # attr_accessible :title, :body
  self.primary_key  = "list_id"
  has_one :list, :foreign_key => "ListingId", :primary_key => "list_id"

  def self.add_and_post(listing)
     post_now = false
     return if (listing.Attention == 0) && (listing.NewBuynow == 0)
     return unless self.find_by_list_id(listing.ListingId).nil?


     if listing.Attention == 1
       post_now = true if ((listing.EndDate - Time.now)/3600).to_i < 24
       info = "Pro bid"
     elsif listing.NewBuynow == 1
       post_now = true
       info = "BN added"
     end

     # TODO Add mail notifications here
     rec = Notifications.new
     rec.list_id = listing.ListingId
     rec.done = post_now
     rec.info = info
     rec.save
     NotifymeMailer.fast_notify([rec]).deliver if post_now
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_on, :category
end

app/models/tokens.rb
class Tokens < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/users.rb
class Users < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :Rated, :BuyerRating, :SellerRating
  self.table_name = "users"
  has_many :lists, :foreign_key => "SellerId"
  has_many :bids, :class_name => "Bids",:foreign_key => "User", :primary_key => "Id"

  def sell_ratio
    self.Listed.to_i > 0 ? self.Sold.to_i * 100 / self.Listed.to_i  : 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
require "datatables.rb"
class ListsController < ApplicationController
  def index
    @@filter_params ||= Hash.new
    params.merge!(@@filter_params)
    respond_to do |format|
      format.html
      format.json do
        @lis  = ListsDatatable.new(@@filter_params, view_context)
        render :json => @lis
      end
    end
  end

  def filter_panel
    @@filter_params = params
    respond_to do |format|
      format.html { redirect_to(:action => 'index') }
      format.json { redirect_to(:action => 'index') }
    end
  end

  def show
    @list = List.find(params[:ListingId])
  end
end

app/controllers/oauth_consumers_controller.rb
require 'oauth/controllers/consumer_controller'
class OauthConsumersController < ApplicationController
  include Oauth::Controllers::ConsumerController
  # Replace this with the equivalent for your authentication framework
  # Eg. for devise
  #
  #   before_filter :authenticate_user!, :only=>:index
  before_filter :login_required, :only=>:index

  def index
    @consumer_tokens=ConsumerToken.all :conditions=>{:user_id=>current_user.id}
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
  end

  def callback
  	super
  end

  def client
    super
  end


  protected

  # Change this to decide where you want to redirect user to after callback is finished.
  # params[:id] holds the service name so you could use this to redirect to various parts
  # of your application depending on what service you're connecting to.
  def go_back
    redirect_to root_url
  end

  # The plugin requires logged_in? to return true or false if the user is logged in. Uncomment and
  # call your auth frameworks equivalent below if different. eg. for devise:
  #
  # def logged_in?
  #   user_signed_in?
  # end

  # The plugin requires current_user to return the current logged in user. Uncomment and
  # call your auth frameworks equivalent below if different.
  # def current_user
  #   current_person
  # end

  # The plugin requires a way to log a user in. Call your auth frameworks equivalent below
  # if different. eg. for devise:
  #
  # def current_user=(user)
  #   sign_in(user)
  # end

  # Override this to deny the user or redirect to a login screen depending on your framework and app
  # if different. eg. for devise:
  #
  # def deny_access!
  #   raise Acl9::AccessDenied
  # end
end

app/controllers/users_controller.rb
require "datatables.rb"

class UsersController < ApplicationController

  def index
    p "+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-+!-"
    respond_to do |format|
      format.html
      format.json do
        @users  = UsersDatatable.new(params, view_context)
        render :json => @users
      end
    end
  end

  def update
    respond_to do |format|
      format.html
      format.json do
        @user = Users.find(params[:id])
        @user.update_attributes(params[:users])
        respond_with_bip(@user)
      end
    end
  end

  def filter_panel
    redirect_to :action => 'index',
                :filter_sold_from => params[:filter_sold_from],
                :filter_sold_to => params[:filter_sold_to],
                :filter_bought_from => params[:filter_bought_from],
                :filter_bought_to => params[:filter_bought_to],
                :filter_with_bids => params[:filter_with_bids]
  end

  def show
    @user = Users.find(params[:id])

    @selectable_table = []

    sorted = [true, false, true, true, false, true, true]
    header = %w[Met Name Value Bidcnt Photo Ending Seller]
    width = %w[6% 30% 12% 6% 20% 14% 12%]

    @selectable_table.push({:label => "Bids", :disabled => Bids.find_all_by_User(@user.Id).empty?, :active => false, :header => header, :sorted => sorted, :width => width})
    @selectable_table.push({:label => "Bought", :disabled => @user.Bought.zero?, :active => false, :header => header, :sorted => sorted, :width => width})
    @selectable_table.push({:label => "Sold", :disabled => @user.Sold.zero?, :active => false, :header => header.take(6).push("Buyer"), :sorted => sorted, :width => width})
    @selectable_table.push({:label => "Listings", :disabled => List.find_all_by_SellerId(@user.Id).empty?, :active => false, :header => header.take(6).push("TopBidder"), :sorted => sorted.take(6).push(false), :width => width})

    @selectable_table.each do |opt|
      next if opt[:disabled]
      if params[:select_table].nil?
        opt[:active] = true
        break
      elsif params[:select_table]==opt[:label]
        opt[:active] = true
      end
    end
  end

  def select_table
    redirect_to(:action => 'show', :select_table => params[:select_table])
  end

  def show_info_table
    respond_to do |format|
      format.html
      format.json do
        @user_info_table  = UserBidsDatatable.new(params, view_context) if (params[:infotype] == "Bids")
        @user_info_table  = UserBoughtDatatable.new(params, view_context) if (params[:infotype] == "Bought")
        @user_info_table  = UserListingsDatatable.new(params, view_context) if (params[:infotype] == "Listings")
        @user_info_table  = UserSoldDatatable.new(params, view_context) if (params[:infotype] == "Sold")
        render :json => @user_info_table
      end
    end
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Selector</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>

  <div id="container">
      <div id="nav">
        <%= link_to_unless_current "Lists", lists_path %> |
        <%= link_to_unless_current "Users", users_path %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_answer_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :content, "Answer" %>
    <%= f.text_field :content %>
    <%# f.check_box :_destroy %>
    <%# f.label :_destroy, "Remove" %>
    <%= link_to_remove_fields "remove", f %>
  </p>
</div>

app/views/lists/_form.html.erb
<%= form_tag({:action => :filter_panel}) do %>
    <h4> Time filter</h4>
    <div id="time_filter" >
    <% time_filters = { "Any" => "Any Time",
                        "finish_8" => "Ending in 8 Hours",
                        "finish_24" => "Ending in 24 Hours",
    } %>
    <% time_filters.each do |name, label| %>
      <%= radio_button_tag(:filter_time, name, checked = params[:filter_time]==name ) %>
      <%= label_tag("filter_time_"+ name, label) %>
    <% end %>
    </div>
    <h4> Listing activity filter</h4>
    <% list_filters = { "buy_now_filter" => "Buy now is added",
                        "repeated_filter" => "Remove repeated",
                        "skip_filter" => "Remove boring",
                        "attention_filter" => "Interesting",

    } %>
    <div id="listing_filter" >
    <% list_filters.each do |name, label| %>
        <%= check_box_tag(name, name, checked = params[name]==name ) %>
        <%= label_tag(name, label) %>
    <% end %>
    </div>
    <h4> Sellers filter</h4>

    <%= submit_tag "Submit" %>
<% end %>

app/views/lists/index.html.erb
<table id="lists" class="display" data-source="<%= lists_url(format: "json") %>">
 <thead>
  <tr>
    <th>Met</th>
    <th>Name</th>
    <th>Value</th>
    <th>Bids</th>
    <th>Image</th>
    <th>End Data</th>
    <th>Seller</th>
    <th>Rating</th>
  </tr>
 </thead>
</table>

<div class="panel">
  <%= render 'form' %>
</div>
<a class="trigger" href="#">Filter</a>
<%#= params.inspect %>

app/views/lists/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Released on:</b>
  <%= @product.released_on.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category.name %>
</p>

<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_tag({:action => :filter_panel}) do %>
    <h4> Sold filter</h4>
    <div id="sold_filter" >
      <%= label_tag(:filter_sold_from, "from") %>
      <%= number_field_tag(:filter_sold_from, params[:filter_sold_from]||0, :in => 0...9999) %>
      <%= label_tag(:filter_sold_to, "to") %>
      <%= number_field_tag(:filter_sold_to, params[:filter_sold_to]||9999, :in => 0...9999) %>
    </div>
    <h4> Bought filter</h4>
    <div id="bought_filter" >
      <%= label_tag(:filter_bought_from, "from") %>
      <%= number_field_tag(:filter_bought_from, params[:filter_bought_from]||0, :in => 0...9999) %>
      <%= label_tag(:filter_bought_to, "to") %>
      <%= number_field_tag(:filter_bought_to, params[:filter_bought_to]||9999, :in => 0...9999) %>
    </div>
    <br>
    <div id="bids_filter" >
      <%= label_tag(:filter_with_bids, "with bids only") %>
      <%= check_box_tag(:filter_with_bids, "checked", checked = params[:filter_with_bids]=="checked" ) %>
    </div>
    <br>
    <%= submit_tag "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<table id="users" class="display" data-source="<%= users_url(format: "json") %>">
  <thead>
  <tr>
    <th>Name</th>
    <th>Exp</th>
    <th>Bought</th>
    <th>Sold</th>
    <th>Listed</th>
    <th>Sold %</th>
    <th>Rated</th>
    <th>Buyer<br>Rating</th>
    <th>Seller<br>Rating</th>
  </tr>
  </thead>
</table>

<div class="panel">
  <%= render 'form' %>
</div>
<a class="trigger" href="#">Filter</a>

app/views/users/show.html.erb
<h2>
  Profile : <%= @user.Name %>
</h2>
<b>Experience</b>
<%= @user.Exp %>
<b>Bought</b>
<%= @user.Bought %>
<b>Sold</b>
<%= @user.Sold %>
<b>Listed</b>
<%= @user.Listed %>
<b>Sell ratio</b>
<%= @user.sell_ratio %>
<br>

<b>Rated</b>
<%= best_in_place @user, :Rated, :type => :select, :collection => [[0, "unrated"], [1, "rated"]] %>
<br>
<b>Buyer Rating</b>
<%= best_in_place @user, :BuyerRating, :type => :select, :collection => [[0, "normal"], [1, "pro"], [2, "expert"]] %>
<br>
<b>Seller Rating</b>
<%= best_in_place @user, :SellerRating, :type => :select, :collection => [[-1, "greedy"], [0, "normal"], [1, "worthy"]] %>
<br>



<div id="select_table" >
  <%= form_tag({:action => "select_table"  } ) do  %>
      <% @selectable_table.each do |opt| %>
          <%=  radio_button_tag :select_table, opt[:label], opt[:active], :disabled => opt[:disabled], :onclick => "this.parentNode.submit();" %>
          <%= label_tag("select_table_"+ opt[:label], opt[:label]) %>
      <% end %>
  <% end %>
</div>


<% @selectable_table.each do |opt| %>
    <% next if !opt[:active] %>

    <%= javascript_tag do %>
        window.datatableheaders = <%= raw opt[:header].map{|rec| rec.downcase}.to_json %>
        window.datatablesorted = <%= raw opt[:sorted].to_json %>
        window.datatablewidth = <%= raw opt[:width].to_json %>
    <% end %>


    <table id="user-info" class="display" data-source="<%= show_info_table_user_url(format: "json")%>" data-infotype=<%=opt[:label]%>>
      <thead>
      <tr>
        <%= raw(opt[:header].map{|hdr| content_tag(:th, hdr)}.join(" ")) %>
      </tr>
      </thead>
    </table>

<% end %>